name: Deploy site to gh-pages

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-deploy:
    name: "Build and Deploy Site to gh-pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
      - run: npm install
      - name: Build Site
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
